# Uncomment this line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '17.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

#target 'Runner' do
#  use_frameworks! :linkage => :static
#
#  use_modular_headers!
#
#  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#  target 'RunnerTests' do
#    inherit! :search_paths
#  end
#end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Determine flavor
  config_name = ENV['FLAVOR'] || 'moon'

  # Pick xcconfig based on flavor
  base_xcconfig = case config_name
                  when 'moon'
                    'Flutter/moonrelease.xcconfig'
                  when 'star'
                    'Flutter/starrelease.xcconfig'
                  else
                    'Flutter/Release.xcconfig'
                  end

  # Apply base configuration for each build configuration
  project.targets.each do |t|
    t.build_configurations.each do |c|
      c.base_configuration_reference = File.join(__dir__, base_xcconfig)
    end
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
