# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(app_identifier: "com.gnkbros.app", type: "appstore",readonly:true, git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"])
    build_app(workspace: "Runner.xcworkspace", scheme: "Release", export_method: "app-store")
    pilot(api_key_path: "fastlane/store.json", skip_waiting_for_build_processing: true)
  end
  
end

# Define all flavor configurations in a single object (Hash)
FLAVOR_CONFIGS = {
  "star" => {
    name: "star",
    bundle_id: "com.gnkbros.app",
    configuration: "starRelease",
    main: "lib/main_star.dart"
  },
  "moon" => {
    name: "moon",
    bundle_id: "com.recode.bookmark",
    configuration: "moonRelease",
    main: "lib/main_moon.dart"
  },
  "ahbenefits" => {
    name: "AH Benefits",
    bundle_id: "com.strive.ahbenefits"
  },
  "pecoconnect" => {
    name: "Peco Connect",
    bundle_id: "com.strive.pecoconnect"
  },
  "geotekconnect" => {
    name: "Geotek Connect",
    bundle_id: "com.strive.geotekconnect"
  },
  "adapt" => {
    name: "Adapt",
    bundle_id: "com.strive.adapt"
  },
  "acrisure" => {
    name: "Acrisure",
    bundle_id: "com.strive.acrisure"
  },
  "aerodyne" => {
    name: "Aerodyne",
    bundle_id: "com.strive.aerodyne"
  },
  "quipthomemedical" => {
    name: "Quipthome Medical",
    bundle_id: "com.strive.quipthomemedical"
  },
  "pregis" => {
    name: "Pregis",
    bundle_id: "com.strive.pregis"
  },
  "pyramidhub" => {
    name: "Pyramid Hub",
    bundle_id: "com.strive.pyramidhub"
  }
}.freeze


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :betaFlavour do |options|
    flavor = options[:flavor]
    config = FLAVOR_CONFIGS[flavor]
    congigname = config[:configuration] || "Release"
  
    setup_ci if ENV['CI']
    match(app_identifier: config[:bundle_id], type: "appstore",readonly: ENV['CI'] ? true : false, git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"])
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build ios --release -t #{config[:main]} --flavor #{flavor} --no-codesign")

    build_app(workspace: "Runner.xcworkspace", scheme: config[:name], export_method: "app-store", configuration: "#{congigname}Release")
    pilot(api_key_path: "fastlane/store.json", skip_waiting_for_build_processing: true)
  end
  
end